app: # 应用基本配置
  env: local # 环境名称
  port: 8080 # 服务监听端口号
  app_name: gin-app111 # 应用名称
  app_url: http://localhost # 应用域名

jwt:
  secret: wudiwangxinyu
  jwt_ttl: 43200

mongodb:
  host: mongodb
  user: root
  password: 123456

jsonrpc:
  host: localhost
  port: 3233
