app: # 应用基本配置
  env: local # 环境名称
  port: 8080 # 服务监听端口号
  app_name: gin-app111 # 应用名称
  app_url: http://localhost # 应用域名

database:
  driver: mysql # 数据库驱动
  host: db # 域名
  port: 3306 # 端口号
  database: gin_test # 数据库名称
  username: test # 用户名
  password: 123456 # 密码
  charset: utf8mb4 # 编码格式
  max_idle_conns: 10 # 空闲连接池中连接的最大数量
  max_open_conns: 100 # 打开数据库连接的最大数量
  log_mode: info # 日志级别
  enable_file_log_writer: true # 是否启用日志文件
  log_filename: sql.log # 日志文件名称

jwt:
  secret: wudiwangxinyu
  jwt_ttl: 43200

mongodb:
  host: mongodb
  user: root
  password: 123456

jsonrpc:
  host: localhost
  port: 3233

elasticsearch:
  host: 192.168.31.232:9200

redis:
  host:
  port:

kafuka:
  host:
  port:

mq:
  host:
  port:

